name: Sync README from testbranch to main

on:
 # Trigger the workflow on any push to testbranch
  push:
    branches:
      - testbranch
   # paths:
   #   - 'README.md' 
 # workflow_dispatch:

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout testbranch
        uses: actions/checkout@v4
        with:
          ref: testbranch
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Copy README.md to temp
        run: cp README.md /tmp/README.md

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Replace README.md from testbranch
        run: |
          cp /tmp/README.md README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Sync README from testbranch"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/SurbhiAgarwal12/testrepo1.git HEAD:main
